openapi: 3.0.0
info:
  title: Meshplay Cloud
  description: Documentation for meshplay Cloud REST APIs
  contact:
    email: support@layer5.io
  version: v0.6.394
servers:
  - url: https://meshplay.layer5.io
    description: Meshplay Cloud production server URL
  - url: https://staging-meshplay.layer5.io
    description: Meshplay Cloud staging server URL
  - url: http://localhost:9876
    description: Meshplay Cloud development server URL (controlled via PORT environment variable)
tags:
  - name: collaboration
    description: APIs for collaboration  
paths:
  /collaboration:
    get:
      tags:
        - collaboration
      operationId: CollaborationHandler
      summary: Collaboration
      description: Collaboration
      security: []
      responses:
        '101':
          description: initate cross server collaboration

