apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshplay-osm
  name: meshplay-osm
spec:
  ports:
    - name: "10009"
      port: 10009
      targetPort: 10009
  selector:
    io.kompose.service: meshplay-osm
status:
  loadBalancer: {}
