
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: meshplay-octarine
  name: meshplay-octarine
spec:
  selector:
    matchLabels:
      io.kompose.service: meshplay-octarine
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: meshplay-octarine
    spec:
      serviceAccount: meshplay-server
      containers:
        - image: khulnasoft/meshplay-octarine:stable-latest
          imagePullPolicy: Always
          name: meshplay-octarine
          ports:
            - containerPort: 10003
          resources: {}
      restartPolicy: Always
status: {}

