name: Meshplay Integrations Updater
on:
  push:
     branches:
       - "master"
     paths:
       - ".github/workflows/integrations-updater.yml"
  schedule:
    - cron:  '0 0 * * *'  # Run the job every day at midnight
  workflow_dispatch:

# This workflow uses the service account: meshplay-integrations-sheet@meshplay-237716.iam.gserviceaccount.com
# See these instructions for setup - https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication

jobs:

  integrations:
    if: github.repository == 'khulnasoft/meshplay'
    runs-on: ubuntu-22.04
    # outputs:
    #   output1: ${{ steps.step1.outputs.test }}
    #   output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Checkout Meshplay repo
        uses: actions/checkout@master
        with:
          path: meshplay
      - name: Checkout Khulnasoft.io repo
        uses: actions/checkout@master
        with:
          repository: khulnasoft/khulnasoft
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: khulnasoft
      - name: Checkout Meshplay.io repo
        uses: actions/checkout@master
        with:
          repository: meshplay/khulnasoft.com
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: khulnasoft.com
      - name: Run utility
        run: cd meshplay/scripts/component_updater; go build main.go; ./main "https://docs.google.com/spreadsheets/d/e/2PACX-1vSgOXuiqbhUgtC9oNbJlz9PYpOEaFVoGNUFMIk4NZciFfQv1ewZg8ahdrWHKI79GkKK9TbmnZx8CqIe/pub?gid=0&single=true&output=csv" --system docs khulnasoft/src/collections/integrations khulnasoft.com/integrations docs/ --published-only
      - name: Commit changes to Khulnasoft.io repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          repository: ./khulnasoft
          commit_user_email: ci@khulnasoft.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "[Docs] Generated documentation for Integration"
          branch: master
      - name: Commit changes to Meshplay.io repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          repository: ./khulnasoft.com
          commit_user_email: ci@khulnasoft.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "[Docs] Generated documentation for Integration"
          branch: master

